ACTUAL_IMAGE_BASE_FOLDER = 'actual'
BASELINE_IMAGE_BASE_FOLDER = 'baseline'
CLEANUP_OPTIONS = [None, 'all_passed', 'diffs_passed', 'actuals_passed']
DIFF_IMAGE_BASE_FOLDER = 'diff'
IMAGES_FOLDER = 'visual_images'
MODE_TEST = 'test'
MODE_BASELINE = 'baseline'
REPORT_FILE = 'visualReport.html'
REPORT_EXPIRATION_THRESHOLD = 10
IMAGE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'bmp', 'raw', 'pdf']
ROBOT_LIBRARY_SCOPE = 'GLOBAL'
ROBOT_LISTENER_API_VERSION = 3